(in-package :postgres-json-test)

(test update-history
  (with-temp-model (with-history)
    (insert 'with-history (obj "a" "b") :use-key 7)
    (update 'with-history 7 (obj "a" "c"))
    (update 'with-history 7 (obj "a" "d"))
    (is (= 2 (length (history 'with-history 7))))
    (with-model-transaction ()
      (insert 'with-history 123 :use-key 8)
      (update 'with-history 8 124)
      (update 'with-history 8 125)
      (is (= 2 (length (history 'with-history 8 :validity-keys-p nil))))))

  (with-temp-model (without-history :keep-history-p nil)
    (insert 'without-history (obj "a" "b") :use-key 7)
    (update 'without-history 7 (obj "a" "c"))
    (update 'without-history 7 (obj "a" "d"))
    (is (zerop (length (history 'without-history 7))))
    (with-model-transaction ()
      (insert 'without-history 123 :use-key 8)
      (update 'without-history 8 124)
      (update 'without-history 8 125)
      (is (zerop (length (history 'without-history 8 :validity-keys-p nil)))))))
